// nationalities.js
export const NATIONALITIES_PT = [
    "Afegã",
    "Albanesa",
    "Algeriana",
    "Americana",
    "Andorrana",
    "Angolana",
    "Argentina",
    "Australiana",
    "Austríaca",
    "Belga",
    "Brasileira",
    "Canadense",
    "Chilena",
    "Chinesa",
    "Colombiana",
    "Coreana",
    "Costa-riquenha",
    "Cubana",
    "Dinamarquesa",
    "Egípcia",
    "Espanhola",
    "Eslovaca",
    "Estadunidense",
    "Francesa",
    "Grega",
    "Holandesa",
    "Indiana",
    "Indonésia",
    "Inglesa",
    "Irlandesa",
    "Italiana",
    "Japonesa",
    "Marroquina",
    "Mexicana",
    "Norueguesa",
    "Peruana",
    "Portuguesa",
    "RussA", // ajuste conforme preferir
    "Sueca",
    "Suíça",
    "Turca",
    "Ucraniana",
    // ...adicione tudo que precisar
];